// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiV5kDnsuj2Bvd6flI1DMw7hsQsybGq4A',
    appId: '1:54661287046:web:86413242a60fff08c31507',
    messagingSenderId: '54661287046',
    projectId: 'enata-7f35e',
    authDomain: 'enata-7f35e.firebaseapp.com',
    storageBucket: 'enata-7f35e.appspot.com',
    measurementId: 'G-BZ8C1328MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH0fdlKdNLd3B8_rNG8L1Wgu68W3uo2Mg',
    appId: '1:54661287046:android:9eb1f405450ab581c31507',
    messagingSenderId: '54661287046',
    projectId: 'enata-7f35e',
    storageBucket: 'enata-7f35e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCm7d5xpncfNRqEs9gMBTNlRB27ycSBwM',
    appId: '1:54661287046:ios:7482cd8bcf903479c31507',
    messagingSenderId: '54661287046',
    projectId: 'enata-7f35e',
    storageBucket: 'enata-7f35e.appspot.com',
    iosBundleId: 'com.example.enata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCm7d5xpncfNRqEs9gMBTNlRB27ycSBwM',
    appId: '1:54661287046:ios:7482cd8bcf903479c31507',
    messagingSenderId: '54661287046',
    projectId: 'enata-7f35e',
    storageBucket: 'enata-7f35e.appspot.com',
    iosBundleId: 'com.example.enata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiV5kDnsuj2Bvd6flI1DMw7hsQsybGq4A',
    appId: '1:54661287046:web:73919cf1e68109bdc31507',
    messagingSenderId: '54661287046',
    projectId: 'enata-7f35e',
    authDomain: 'enata-7f35e.firebaseapp.com',
    storageBucket: 'enata-7f35e.appspot.com',
    measurementId: 'G-55FVGXTLQP',
  );

}